version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: trilhas_postgres
    restart: always
    environment:
      POSTGRES_USER: trilhas_user
      POSTGRES_PASSWORD: trilhas_password
      POSTGRES_DB: trilhas_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: